#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShoppingHelper.Resource", IsApplication=true)]

namespace ShoppingHelper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::ShoppingHelper.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::ShoppingHelper.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_white_36dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_local_grocery_store_white_36dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_mode_edit_white_36dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_sort_by_alpha_white_36dp = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int AddProductMenuItem = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int AddProductNameEditText = 2131034113;
			
			// aapt resource value: 0x7f050017
			public const int AddShoppingList = 2131034135;
			
			// aapt resource value: 0x7f050002
			public const int AddShoppingListNameEditText = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int ProductRowView = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int ProductSelectionRecyclerView = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ProductSelectionRowView = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int ProductSelectionTopToolbar = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int ShoppingListRecyclerView = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int ShoppingListRowView = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int ShoppingListRowViewCountTextView = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int ShoppingListRowViewDescriptionTextView = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int ShoppingListTopToolbar = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int SortByNameMenuItem = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int StartShoppingListTopToolbar = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int StartShoppingRecyclerView = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int Toolbar = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int product_selection_description_textview = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int product_selection_less_button = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int product_selection_more_button = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int product_selection_quantity_textview = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int start_shopping_menu_edit = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int start_shopping_menu_share = 2131034137;
			
			// aapt resource value: 0x7f050007
			public const int start_shopping_product_description_textview = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int start_shopping_product_quantity_textview = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddProduct = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddShoppingList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProductRowView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProductSelection = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ProductSelectionRowView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ShoppingListRowView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int StartShopping = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Toolbar = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int EditShoppingListTopMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ShoppingListTopMenu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int StartShoppingTopMenu = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int Edit = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int New = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int ProductName = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int ProductSelection = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int ProductSelectionToolbarSubtitle = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int Products = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int Share = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int ShoppingListName = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ShoppingLists = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int ShoppingListsToolbarSubtitle = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int Sort = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int StartShoppingToolbarSubtitle = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ToolbarSubtitleAppearance = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int myTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
